#!/usr/bin/env ruby

require 'bundler/setup'
require 'udipity'

options = Udipity::CLI.parse(ARGV)

mode = options.delete(:mode)

begin
  mode.start(options)
rescue SystemExit, Interrupt
  # Do nothing, just avoid the stacktrace caused by the interrupt
end
